In [2]:
import numpy as np 

In [3]:
a=np.array([4,6,8])

In [4]:
a

array([4, 6, 8])

In [5]:
b=np.array([[8.0,7.0,6.0],[5.0,4.0,3.0]])

In [6]:
print(b)

[[8. 7. 6.]
 [5. 4. 3.]]


### Get Dimension

In [7]:
a.ndim

1

In [8]:
b.ndim

2

### Get Shape 

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

### Get Type and Shape

In [11]:
a.dtype #get type

dtype('int64')

In [12]:
b.dtype 

dtype('float64')

In [13]:
a.size

3

In [14]:
b.size 

6

In [15]:
a.itemsize

8

In [16]:
b.itemsize

8

In [19]:
b.nbytes #get total size

48

### Accessing/Changing specific elements ,rows,columns etc

In [20]:
k = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[4 6 8]


In [25]:
k.shape

(2, 7)

In [26]:
#get specific element via rows and colummns as [r,c]
k[1][5] # or k[1][-1]

13

In [27]:
# get specific row
k[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# get specific column
k[: ,2]

array([ 3, 10])

In [29]:
#[startindex:endindex:stepsize]
k[0, 1:6:2]

array([2, 4, 6])

In [32]:
k[1,5]=20 #assigned new number to that particular element via its index

In [33]:
k

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [34]:
k[:,2]=[1,2]
k

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

### 3d exmaple

In [41]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [42]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [43]:
# get specific element (works outside in)
b[0,1,1]

4

In [44]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [45]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Intialize different type of arrays

In [47]:
 # All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [51]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [52]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [55]:
np.full(a.shape,4)

array([4, 4, 4])

In [56]:
np.full_like(a,4)

array([4, 4, 4])

In [58]:
# random decimal numbers
np.random.rand(4,2)

array([[0.85077984, 0.66069883],
       [0.2638461 , 0.54192444],
       [0.052836  , 0.79449188],
       [0.81128578, 0.9035321 ]])

In [59]:
# random decimal numbers
np.random.rand(4,2,3)

array([[[0.93585176, 0.17378646, 0.03144491],
        [0.79544448, 0.12540555, 0.07177986]],

       [[0.5419301 , 0.60799769, 0.76382395],
        [0.2677338 , 0.78346327, 0.22605491]],

       [[0.61625419, 0.85561802, 0.6130731 ],
        [0.00256026, 0.12780702, 0.62884844]],

       [[0.42746878, 0.4439687 , 0.18491445],
        [0.3687733 , 0.03580703, 0.01029596]]])

In [60]:
# random decimal numbers while shape input
np.random.random_sample(k.shape)

array([[0.13857567, 0.46124264, 0.08059071, 0.28897782, 0.72944334,
        0.03105334, 0.20202645],
       [0.26504894, 0.84638121, 0.041708  , 0.57408609, 0.01771924,
        0.55527685, 0.13510672]])

In [61]:
# random integer values
np.random.randint(7,size=(3,3))

array([[6, 4, 4],
       [2, 4, 3],
       [2, 4, 2]])

In [62]:
np.random.randint(4,7,size=(3,3))

array([[5, 4, 4],
       [5, 6, 4],
       [5, 5, 5]])

In [64]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
arr=np.array([1,2,3]) #1d array 
r1=np.repeat(arr,3,axis=0) #repeat 3 times
print(r1)

[1 1 1 2 2 2 3 3 3]


In [67]:
arr=np.array([[1,2,3]]) #2d array
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
output =np.ones((5,5))

In [69]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
z=np.zeros((3,3))

In [72]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [73]:
z[1,1]=9

In [74]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [75]:
output[1:4,1:4]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## be careful when copying arrays!!

In [76]:
a=np.array([1,2,3])
b=a
b[0]=100 #even though we change the value in b but it also changes the val in a as both point to same array
a

array([100,   2,   3])

In [77]:
# to prevent above we do
a=np.array([1,2,3])
b=a.copy()
b[0]=100
a

array([1, 2, 3])

# Mathematics

In [79]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [80]:
a+2

array([3, 4, 5, 6])

In [81]:
a-2

array([-1,  0,  1,  2])

In [82]:
a*2

array([2, 4, 6, 8])

In [83]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [85]:
a+=2
a

array([5, 6, 7, 8])

In [86]:
b=np.array([1,0,1,0])
a+b

array([6, 6, 8, 8])

In [87]:
a**2

array([25, 36, 49, 64])

In [88]:
# take the sin
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [89]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

In [90]:
## refer docs for more functions

### Linear Algebra

In [92]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [96]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [98]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [99]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.min(stats)

1

In [101]:
np.max(stats)

6

In [103]:
np.min(stats,axis=1) #min of first row and second row respectively

array([1, 4])

In [104]:
np.sum(stats)

21

In [105]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganising array

In [106]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [107]:
after=before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [108]:
after=before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [109]:
#Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [110]:
#Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [113]:
# Horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Load Data from file

In [115]:
filedata = np.genfromtxt('sample3.txt', delimiter=',')

In [116]:
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [118]:
filedata=filedata.astype('int32')

In [121]:
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking Advanced indexing

In [122]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [123]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [124]:
# you can index with a list in Numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [126]:
np.any(filedata>50,axis=0) #axis=0 for columns and axis=1 for rows

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [127]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [128]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [129]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [131]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [132]:
(~((filedata>50)&(filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])